### PR TITLE
Subscription support

### PR DESCRIPTION
**Pull request by wtrocki**
## Motivation

Add subscription call and check if that works.
Refactor code to use common fragment between subscription and list query.
Investigating some issue currently

### CODE REVIEW

**Comment by wtrocki** [comment]
Requires change in SDK: https://github.com/aerogear/aerogear-ios-sdk/pull/146

**Comment by wtrocki** [comment]
@danielpassos FYI outstanding issue to resolve,

**Comment by danielpassos** [comment]
@wtrocki It's in my queue

**Comment by danielpassos** [comment]
@wtrocki I just rebased it from master

**Comment by danielpassos** [comment]
I have tested it using the [aerogear-ios-example-apps#AEROGEAR-7873](https://github.com/aerogear/aerogear-ios-example-apps/tree/AEROGEAR-7873) how fix the meme schema problem. This branch was created in top of this

**Review by danielpassos — APPROVED** [review]
I have tested it using the [aerogear-ios-example-apps#AEROGEAR-7873](https://github.com/aerogear/aerogear-ios-example-apps/tree/AEROGEAR-7873) to fix the meme schema problem. This branch was created on top of this

**Pull request merged**
